// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: crates/crates.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PlanSDK.Crates {

  /// <summary>Holder for reflection information generated from crates/crates.proto</summary>
  public static partial class CratesReflection {

    #region Descriptor
    /// <summary>File descriptor for crates/crates.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CratesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNjcmF0ZXMvY3JhdGVzLnByb3RvEgZjcmF0ZXMiggIKCkFzc2V0RW50cnkS",
            "JgoKQXNzZXRGbGFncxgBIAEoDjISLmNyYXRlcy5Bc3NldEZsYWdzEhIKCkJy",
            "b3dzZVBhdGgYAiABKAkSDAoETmFtZRgDIAEoCRIOCgZOYW1lSUQYBCABKAkS",
            "DwoHQ2VudGVyWBgFIAEoAhIPCgdDZW50ZXJZGAYgASgCEg8KB0NlbnRlcloY",
            "ByABKAISEAoIRXh0ZW50c1gYCiABKAISEAoIRXh0ZW50c1kYCyABKAISEAoI",
            "RXh0ZW50c1oYDCABKAISEAoITG9jYWxVUkkYHiABKAkSDAoEVGFncxgfIAEo",
            "CRIRCglTaG9ydERlc2MYICABKAkidAoOQnVuZGxlTWFuaWZlc3QSEwoLQnVu",
            "ZGxlVGl0bGUYAiABKAkSFAoMQnVuZGxlTmFtZUlEGAMgASgJEiIKBkFzc2V0",
            "cxgKIAMoCzISLmNyYXRlcy5Bc3NldEVudHJ5EhMKC0xvYWRBbGxIaW50GBQg",
            "ASgIIvYBCglDcmF0ZUluZm8SDgoGSW5zdElEGAEgASgNEhIKCkhvbWVEb21h",
            "aW4YAyABKAkSDgoGTmFtZUlEGAUgASgJEg0KBVRpdGxlGAogASgJEhEKCVNo",
            "b3J0RGVzYxgLIAEoCRIMCgRUYWdzGA8gASgJEhMKC1RpbWVDcmVhdGVkGB4g",
            "ASgDEhEKCVRpbWVCdWlsdBgfIAEoAxIUCgxNYWpvclZlcnNpb24YKCABKAUS",
            "FAoMTWlub3JWZXJzaW9uGCkgASgFEhMKC0J1aWxkTnVtYmVyGCogASgFEg8K",
            "B0J1aWxkSUQYLSABKAkSCwoDVVJMGDIgASgJInEKDUNyYXRlTWFuaWZlc3QS",
            "HwoESW5mbxgBIAEoCzIRLmNyYXRlcy5DcmF0ZUluZm8SFgoOSWNvbkJ1bmRs",
            "ZU5hbWUYBSABKAkSJwoHQnVuZGxlcxgKIAMoCzIWLmNyYXRlcy5CdW5kbGVN",
            "YW5pZmVzdCJWCg1DcmF0ZVNuYXBzaG90Eg0KBVJldklEGAEgASgDEhMKC0Rv",
            "d25sb2FkVVJMGAMgASgJEiEKBkNyYXRlcxgKIAMoCzIRLmNyYXRlcy5DcmF0",
            "ZUluZm8qwQEKCkFzc2V0RmxhZ3MSCwoHTm9GbGFncxAAEgsKB0lzVGV4MkQQ",
            "ARIMCghJc1Nwcml0ZRACEg4KCklzTWF0ZXJpYWwQBBIPCgtJc1BsYWNlYWJs",
            "ZRAIEhMKD0lzUmVjdFRyYW5zZm9ybRAQEggKBElzVUkQIBIMCgdIYXNJY29u",
            "EIACEg4KCUlzUHJpdmF0ZRCABBINCghJc1NreWJveBCACBIOCglBdXRvU2Nh",
            "bGUQgBASDgoJSXNTdXJmYWNlEIAgQhGqAg5QbGFuU0RLLkNyYXRlc2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PlanSDK.Crates.AssetFlags), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PlanSDK.Crates.AssetEntry), global::PlanSDK.Crates.AssetEntry.Parser, new[]{ "AssetFlags", "BrowsePath", "Name", "NameID", "CenterX", "CenterY", "CenterZ", "ExtentsX", "ExtentsY", "ExtentsZ", "LocalURI", "Tags", "ShortDesc" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlanSDK.Crates.BundleManifest), global::PlanSDK.Crates.BundleManifest.Parser, new[]{ "BundleTitle", "BundleNameID", "Assets", "LoadAllHint" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlanSDK.Crates.CrateInfo), global::PlanSDK.Crates.CrateInfo.Parser, new[]{ "InstID", "HomeDomain", "NameID", "Title", "ShortDesc", "Tags", "TimeCreated", "TimeBuilt", "MajorVersion", "MinorVersion", "BuildNumber", "BuildID", "URL" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlanSDK.Crates.CrateManifest), global::PlanSDK.Crates.CrateManifest.Parser, new[]{ "Info", "IconBundleName", "Bundles" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PlanSDK.Crates.CrateSnapshot), global::PlanSDK.Crates.CrateSnapshot.Parser, new[]{ "RevID", "DownloadURL", "Crates" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum AssetFlags {
    [pbr::OriginalName("NoFlags")] NoFlags = 0,
    [pbr::OriginalName("IsTex2D")] IsTex2D = 1,
    [pbr::OriginalName("IsSprite")] IsSprite = 2,
    [pbr::OriginalName("IsMaterial")] IsMaterial = 4,
    [pbr::OriginalName("IsPlaceable")] IsPlaceable = 8,
    [pbr::OriginalName("IsRectTransform")] IsRectTransform = 16,
    /// <summary>
    /// Is UI means that this item is for UI/UX and meets additional requirements.
    /// </summary>
    [pbr::OriginalName("IsUI")] IsUi = 32,
    /// <summary>
    /// HasIcon means that this Asset includes an icon with the same name (and has IsIcon set),
    /// </summary>
    [pbr::OriginalName("HasIcon")] HasIcon = 256,
    /// <summary>
    /// IsPrivate means this item is not intended for general use and is not normally visible. 
    /// </summary>
    [pbr::OriginalName("IsPrivate")] IsPrivate = 512,
    /// <summary>
    /// IsSkybox means this is a transform containing a Skybox component.
    /// </summary>
    [pbr::OriginalName("IsSkybox")] IsSkybox = 1024,
    /// <summary>
    /// AutoScale means this asset should be placed with auto scale enabled by default.
    /// </summary>
    [pbr::OriginalName("AutoScale")] AutoScale = 2048,
    /// <summary>
    /// IsSurface means this asset behaves like terrain and/or should be considered a constituent part of a scene.
    /// These objects should be opaque and have colliders attached to them
    /// e.g.  a building, a terrain formation, a wall
    /// </summary>
    [pbr::OriginalName("IsSurface")] IsSurface = 4096,
  }

  #endregion

  #region Messages
  public sealed partial class AssetEntry : pb::IMessage<AssetEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AssetEntry> _parser = new pb::MessageParser<AssetEntry>(() => new AssetEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AssetEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlanSDK.Crates.CratesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssetEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssetEntry(AssetEntry other) : this() {
      assetFlags_ = other.assetFlags_;
      browsePath_ = other.browsePath_;
      name_ = other.name_;
      nameID_ = other.nameID_;
      centerX_ = other.centerX_;
      centerY_ = other.centerY_;
      centerZ_ = other.centerZ_;
      extentsX_ = other.extentsX_;
      extentsY_ = other.extentsY_;
      extentsZ_ = other.extentsZ_;
      localURI_ = other.localURI_;
      tags_ = other.tags_;
      shortDesc_ = other.shortDesc_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AssetEntry Clone() {
      return new AssetEntry(this);
    }

    /// <summary>Field number for the "AssetFlags" field.</summary>
    public const int AssetFlagsFieldNumber = 1;
    private global::PlanSDK.Crates.AssetFlags assetFlags_ = global::PlanSDK.Crates.AssetFlags.NoFlags;
    /// <summary>
    /// Flags specifies properties about this asset.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PlanSDK.Crates.AssetFlags AssetFlags {
      get { return assetFlags_; }
      set {
        assetFlags_ = value;
      }
    }

    /// <summary>Field number for the "BrowsePath" field.</summary>
    public const int BrowsePathFieldNumber = 2;
    private string browsePath_ = "";
    /// <summary>
    /// DEPRECATED -- this disappears when we have a real browsing system (vs a HFS/path based system)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BrowsePath {
      get { return browsePath_; }
      set {
        browsePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NameID" field.</summary>
    public const int NameIDFieldNumber = 4;
    private string nameID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameID {
      get { return nameID_; }
      set {
        nameID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CenterX" field.</summary>
    public const int CenterXFieldNumber = 5;
    private float centerX_;
    /// <summary>
    /// CenterX and CenterZ specify the positional center of this asset (and are typically 0).
    /// CenterY is the distance above the baseline (y=0) to the y center-point height of this asset.
    /// Y is considered to be the *vertical* (up) direction and by convention rest on the plane y=0.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float CenterX {
      get { return centerX_; }
      set {
        centerX_ = value;
      }
    }

    /// <summary>Field number for the "CenterY" field.</summary>
    public const int CenterYFieldNumber = 6;
    private float centerY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float CenterY {
      get { return centerY_; }
      set {
        centerY_ = value;
      }
    }

    /// <summary>Field number for the "CenterZ" field.</summary>
    public const int CenterZFieldNumber = 7;
    private float centerZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float CenterZ {
      get { return centerZ_; }
      set {
        centerZ_ = value;
      }
    }

    /// <summary>Field number for the "ExtentsX" field.</summary>
    public const int ExtentsXFieldNumber = 10;
    private float extentsX_;
    /// <summary>
    /// Extents specify the extents as distance from the center to the extent of the asset on each axis.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float ExtentsX {
      get { return extentsX_; }
      set {
        extentsX_ = value;
      }
    }

    /// <summary>Field number for the "ExtentsY" field.</summary>
    public const int ExtentsYFieldNumber = 11;
    private float extentsY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float ExtentsY {
      get { return extentsY_; }
      set {
        extentsY_ = value;
      }
    }

    /// <summary>Field number for the "ExtentsZ" field.</summary>
    public const int ExtentsZFieldNumber = 12;
    private float extentsZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float ExtentsZ {
      get { return extentsZ_; }
      set {
        extentsZ_ = value;
      }
    }

    /// <summary>Field number for the "LocalURI" field.</summary>
    public const int LocalURIFieldNumber = 30;
    private string localURI_ = "";
    /// <summary>
    /// Ignored; available for dynamic use.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LocalURI {
      get { return localURI_; }
      set {
        localURI_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Tags" field.</summary>
    public const int TagsFieldNumber = 31;
    private string tags_ = "";
    /// <summary>
    /// Comma delimited and whitespace-trimmed list of of tags  
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Tags {
      get { return tags_; }
      set {
        tags_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ShortDesc" field.</summary>
    public const int ShortDescFieldNumber = 32;
    private string shortDesc_ = "";
    /// <summary>
    /// A short phrase or fragment describing this asset, starting with an article where appropriate. e.g.:
    ///      "typical 6 crew member fire truck"
    ///      "leading U.S. naval ship-based helicopter"
    ///      "Texas capital building located in Austin"
    ///      "animated scared-geometry inspired flat seal"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ShortDesc {
      get { return shortDesc_; }
      set {
        shortDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AssetEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AssetEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AssetFlags != other.AssetFlags) return false;
      if (BrowsePath != other.BrowsePath) return false;
      if (Name != other.Name) return false;
      if (NameID != other.NameID) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CenterX, other.CenterX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CenterY, other.CenterY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CenterZ, other.CenterZ)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ExtentsX, other.ExtentsX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ExtentsY, other.ExtentsY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ExtentsZ, other.ExtentsZ)) return false;
      if (LocalURI != other.LocalURI) return false;
      if (Tags != other.Tags) return false;
      if (ShortDesc != other.ShortDesc) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AssetFlags != global::PlanSDK.Crates.AssetFlags.NoFlags) hash ^= AssetFlags.GetHashCode();
      if (BrowsePath.Length != 0) hash ^= BrowsePath.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (NameID.Length != 0) hash ^= NameID.GetHashCode();
      if (CenterX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CenterX);
      if (CenterY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CenterY);
      if (CenterZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CenterZ);
      if (ExtentsX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ExtentsX);
      if (ExtentsY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ExtentsY);
      if (ExtentsZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ExtentsZ);
      if (LocalURI.Length != 0) hash ^= LocalURI.GetHashCode();
      if (Tags.Length != 0) hash ^= Tags.GetHashCode();
      if (ShortDesc.Length != 0) hash ^= ShortDesc.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AssetFlags != global::PlanSDK.Crates.AssetFlags.NoFlags) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AssetFlags);
      }
      if (BrowsePath.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BrowsePath);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (NameID.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NameID);
      }
      if (CenterX != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(CenterX);
      }
      if (CenterY != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(CenterY);
      }
      if (CenterZ != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(CenterZ);
      }
      if (ExtentsX != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(ExtentsX);
      }
      if (ExtentsY != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(ExtentsY);
      }
      if (ExtentsZ != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(ExtentsZ);
      }
      if (LocalURI.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(LocalURI);
      }
      if (Tags.Length != 0) {
        output.WriteRawTag(250, 1);
        output.WriteString(Tags);
      }
      if (ShortDesc.Length != 0) {
        output.WriteRawTag(130, 2);
        output.WriteString(ShortDesc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AssetFlags != global::PlanSDK.Crates.AssetFlags.NoFlags) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AssetFlags);
      }
      if (BrowsePath.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BrowsePath);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (NameID.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NameID);
      }
      if (CenterX != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(CenterX);
      }
      if (CenterY != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(CenterY);
      }
      if (CenterZ != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(CenterZ);
      }
      if (ExtentsX != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(ExtentsX);
      }
      if (ExtentsY != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(ExtentsY);
      }
      if (ExtentsZ != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(ExtentsZ);
      }
      if (LocalURI.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(LocalURI);
      }
      if (Tags.Length != 0) {
        output.WriteRawTag(250, 1);
        output.WriteString(Tags);
      }
      if (ShortDesc.Length != 0) {
        output.WriteRawTag(130, 2);
        output.WriteString(ShortDesc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AssetFlags != global::PlanSDK.Crates.AssetFlags.NoFlags) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AssetFlags);
      }
      if (BrowsePath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BrowsePath);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (NameID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameID);
      }
      if (CenterX != 0F) {
        size += 1 + 4;
      }
      if (CenterY != 0F) {
        size += 1 + 4;
      }
      if (CenterZ != 0F) {
        size += 1 + 4;
      }
      if (ExtentsX != 0F) {
        size += 1 + 4;
      }
      if (ExtentsY != 0F) {
        size += 1 + 4;
      }
      if (ExtentsZ != 0F) {
        size += 1 + 4;
      }
      if (LocalURI.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(LocalURI);
      }
      if (Tags.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Tags);
      }
      if (ShortDesc.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ShortDesc);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AssetEntry other) {
      if (other == null) {
        return;
      }
      if (other.AssetFlags != global::PlanSDK.Crates.AssetFlags.NoFlags) {
        AssetFlags = other.AssetFlags;
      }
      if (other.BrowsePath.Length != 0) {
        BrowsePath = other.BrowsePath;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.NameID.Length != 0) {
        NameID = other.NameID;
      }
      if (other.CenterX != 0F) {
        CenterX = other.CenterX;
      }
      if (other.CenterY != 0F) {
        CenterY = other.CenterY;
      }
      if (other.CenterZ != 0F) {
        CenterZ = other.CenterZ;
      }
      if (other.ExtentsX != 0F) {
        ExtentsX = other.ExtentsX;
      }
      if (other.ExtentsY != 0F) {
        ExtentsY = other.ExtentsY;
      }
      if (other.ExtentsZ != 0F) {
        ExtentsZ = other.ExtentsZ;
      }
      if (other.LocalURI.Length != 0) {
        LocalURI = other.LocalURI;
      }
      if (other.Tags.Length != 0) {
        Tags = other.Tags;
      }
      if (other.ShortDesc.Length != 0) {
        ShortDesc = other.ShortDesc;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AssetFlags = (global::PlanSDK.Crates.AssetFlags) input.ReadEnum();
            break;
          }
          case 18: {
            BrowsePath = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            NameID = input.ReadString();
            break;
          }
          case 45: {
            CenterX = input.ReadFloat();
            break;
          }
          case 53: {
            CenterY = input.ReadFloat();
            break;
          }
          case 61: {
            CenterZ = input.ReadFloat();
            break;
          }
          case 85: {
            ExtentsX = input.ReadFloat();
            break;
          }
          case 93: {
            ExtentsY = input.ReadFloat();
            break;
          }
          case 101: {
            ExtentsZ = input.ReadFloat();
            break;
          }
          case 242: {
            LocalURI = input.ReadString();
            break;
          }
          case 250: {
            Tags = input.ReadString();
            break;
          }
          case 258: {
            ShortDesc = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AssetFlags = (global::PlanSDK.Crates.AssetFlags) input.ReadEnum();
            break;
          }
          case 18: {
            BrowsePath = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            NameID = input.ReadString();
            break;
          }
          case 45: {
            CenterX = input.ReadFloat();
            break;
          }
          case 53: {
            CenterY = input.ReadFloat();
            break;
          }
          case 61: {
            CenterZ = input.ReadFloat();
            break;
          }
          case 85: {
            ExtentsX = input.ReadFloat();
            break;
          }
          case 93: {
            ExtentsY = input.ReadFloat();
            break;
          }
          case 101: {
            ExtentsZ = input.ReadFloat();
            break;
          }
          case 242: {
            LocalURI = input.ReadString();
            break;
          }
          case 250: {
            Tags = input.ReadString();
            break;
          }
          case 258: {
            ShortDesc = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BundleManifest : pb::IMessage<BundleManifest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BundleManifest> _parser = new pb::MessageParser<BundleManifest>(() => new BundleManifest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BundleManifest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlanSDK.Crates.CratesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BundleManifest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BundleManifest(BundleManifest other) : this() {
      bundleTitle_ = other.bundleTitle_;
      bundleNameID_ = other.bundleNameID_;
      assets_ = other.assets_.Clone();
      loadAllHint_ = other.loadAllHint_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BundleManifest Clone() {
      return new BundleManifest(this);
    }

    /// <summary>Field number for the "BundleTitle" field.</summary>
    public const int BundleTitleFieldNumber = 2;
    private string bundleTitle_ = "";
    /// <summary>
    /// BundleTitle is how the outside world sees this bundle and has no other impact.
    /// This means it can change from build to build and contain any Unicode characters.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BundleTitle {
      get { return bundleTitle_; }
      set {
        bundleTitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BundleNameID" field.</summary>
    public const int BundleNameIDFieldNumber = 3;
    private string bundleNameID_ = "";
    /// <summary>
    /// BundleNameID is how this bundle is internally identified and expressed the filename of this bundle
    /// This is case sensitive, contains only path-safe characters (sans /:\&lt;>|?*\"), and does not terminate in '.' or whitespace.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BundleNameID {
      get { return bundleNameID_; }
      set {
        bundleNameID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Assets" field.</summary>
    public const int AssetsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::PlanSDK.Crates.AssetEntry> _repeated_assets_codec
        = pb::FieldCodec.ForMessage(82, global::PlanSDK.Crates.AssetEntry.Parser);
    private readonly pbc::RepeatedField<global::PlanSDK.Crates.AssetEntry> assets_ = new pbc::RepeatedField<global::PlanSDK.Crates.AssetEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::PlanSDK.Crates.AssetEntry> Assets {
      get { return assets_; }
    }

    /// <summary>Field number for the "LoadAllHint" field.</summary>
    public const int LoadAllHintFieldNumber = 20;
    private bool loadAllHint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool LoadAllHint {
      get { return loadAllHint_; }
      set {
        loadAllHint_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BundleManifest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BundleManifest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BundleTitle != other.BundleTitle) return false;
      if (BundleNameID != other.BundleNameID) return false;
      if(!assets_.Equals(other.assets_)) return false;
      if (LoadAllHint != other.LoadAllHint) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BundleTitle.Length != 0) hash ^= BundleTitle.GetHashCode();
      if (BundleNameID.Length != 0) hash ^= BundleNameID.GetHashCode();
      hash ^= assets_.GetHashCode();
      if (LoadAllHint != false) hash ^= LoadAllHint.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BundleTitle.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BundleTitle);
      }
      if (BundleNameID.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BundleNameID);
      }
      assets_.WriteTo(output, _repeated_assets_codec);
      if (LoadAllHint != false) {
        output.WriteRawTag(160, 1);
        output.WriteBool(LoadAllHint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BundleTitle.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BundleTitle);
      }
      if (BundleNameID.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BundleNameID);
      }
      assets_.WriteTo(ref output, _repeated_assets_codec);
      if (LoadAllHint != false) {
        output.WriteRawTag(160, 1);
        output.WriteBool(LoadAllHint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BundleTitle.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BundleTitle);
      }
      if (BundleNameID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BundleNameID);
      }
      size += assets_.CalculateSize(_repeated_assets_codec);
      if (LoadAllHint != false) {
        size += 2 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BundleManifest other) {
      if (other == null) {
        return;
      }
      if (other.BundleTitle.Length != 0) {
        BundleTitle = other.BundleTitle;
      }
      if (other.BundleNameID.Length != 0) {
        BundleNameID = other.BundleNameID;
      }
      assets_.Add(other.assets_);
      if (other.LoadAllHint != false) {
        LoadAllHint = other.LoadAllHint;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            BundleTitle = input.ReadString();
            break;
          }
          case 26: {
            BundleNameID = input.ReadString();
            break;
          }
          case 82: {
            assets_.AddEntriesFrom(input, _repeated_assets_codec);
            break;
          }
          case 160: {
            LoadAllHint = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            BundleTitle = input.ReadString();
            break;
          }
          case 26: {
            BundleNameID = input.ReadString();
            break;
          }
          case 82: {
            assets_.AddEntriesFrom(ref input, _repeated_assets_codec);
            break;
          }
          case 160: {
            LoadAllHint = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// CrateInfo represents a Crate, the fundamental unit of PLAN's asset/package manager. 
  /// </summary>
  public sealed partial class CrateInfo : pb::IMessage<CrateInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CrateInfo> _parser = new pb::MessageParser<CrateInfo>(() => new CrateInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CrateInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlanSDK.Crates.CratesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrateInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrateInfo(CrateInfo other) : this() {
      instID_ = other.instID_;
      homeDomain_ = other.homeDomain_;
      nameID_ = other.nameID_;
      title_ = other.title_;
      shortDesc_ = other.shortDesc_;
      tags_ = other.tags_;
      timeCreated_ = other.timeCreated_;
      timeBuilt_ = other.timeBuilt_;
      majorVersion_ = other.majorVersion_;
      minorVersion_ = other.minorVersion_;
      buildNumber_ = other.buildNumber_;
      buildID_ = other.buildID_;
      uRL_ = other.uRL_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrateInfo Clone() {
      return new CrateInfo(this);
    }

    /// <summary>Field number for the "InstID" field.</summary>
    public const int InstIDFieldNumber = 1;
    private uint instID_;
    /// <summary>
    /// InstID is 0 by default and reserved for a runtime manager to reference a crate via issuing integers.
    /// If non-zero, it will not change and no other instance will have the same value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint InstID {
      get { return instID_; }
      set {
        instID_ = value;
      }
    }

    /// <summary>Field number for the "HomeDomain" field.</summary>
    public const int HomeDomainFieldNumber = 3;
    private string homeDomain_ = "";
    /// <summary>
    /// HomeDomain identifies the publisher of this asset crate
    ///
    /// e.g. 
    ///    "plan-systems.org"
    ///    "themushroom.farm" 
    ///    "the-smiths.family" 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HomeDomain {
      get { return homeDomain_; }
      set {
        homeDomain_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NameID" field.</summary>
    public const int NameIDFieldNumber = 5;
    private string nameID_ = "";
    /// <summary>
    /// NameID uniquely identifies this crate (for the given crate's publisher/home domain).
    /// This name identifies this crate and is permanent (or else existing path refs will be broken)
    ///
    /// e.g. 
    ///    "plan-app"
    ///    "about-plan-systems"
    ///    "welcome-to-plan"
    ///    "common"     
    ///    "mycology-101"     
    ///    "mycology-201"     
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameID {
      get { return nameID_; }
      set {
        nameID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Title" field.</summary>
    public const int TitleFieldNumber = 10;
    private string title_ = "";
    /// <summary>
    /// Title is a human-readable title for this crate and can change without any repercussions (i.e. is purely optical)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ShortDesc" field.</summary>
    public const int ShortDescFieldNumber = 11;
    private string shortDesc_ = "";
    /// <summary>
    /// ShortDesc describes this crate in a brief phrase
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ShortDesc {
      get { return shortDesc_; }
      set {
        shortDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Tags" field.</summary>
    public const int TagsFieldNumber = 15;
    private string tags_ = "";
    /// <summary>
    /// Comma delimited and whitespace-trimmed list of of tags  
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Tags {
      get { return tags_; }
      set {
        tags_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TimeCreated" field.</summary>
    public const int TimeCreatedFieldNumber = 30;
    private long timeCreated_;
    /// <summary>
    /// TimeCreated is UTC value (in seconds) when this crate first created (and does not change)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TimeCreated {
      get { return timeCreated_; }
      set {
        timeCreated_ = value;
      }
    }

    /// <summary>Field number for the "TimeBuilt" field.</summary>
    public const int TimeBuiltFieldNumber = 31;
    private long timeBuilt_;
    /// <summary>
    /// TimeBuilt is UTC value (in seconds) when this crate was built.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TimeBuilt {
      get { return timeBuilt_; }
      set {
        timeBuilt_ = value;
      }
    }

    /// <summary>Field number for the "MajorVersion" field.</summary>
    public const int MajorVersionFieldNumber = 40;
    private int majorVersion_;
    /// <summary>
    /// VersionID uniquely identifies this build and has the form "v{MajorNum}.{MinorNum}.{BuildNum}"
    /// e.g. "v1.11.201"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MajorVersion {
      get { return majorVersion_; }
      set {
        majorVersion_ = value;
      }
    }

    /// <summary>Field number for the "MinorVersion" field.</summary>
    public const int MinorVersionFieldNumber = 41;
    private int minorVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MinorVersion {
      get { return minorVersion_; }
      set {
        minorVersion_ = value;
      }
    }

    /// <summary>Field number for the "BuildNumber" field.</summary>
    public const int BuildNumberFieldNumber = 42;
    private int buildNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuildNumber {
      get { return buildNumber_; }
      set {
        buildNumber_ = value;
      }
    }

    /// <summary>Field number for the "BuildID" field.</summary>
    public const int BuildIDFieldNumber = 45;
    private string buildID_ = "";
    /// <summary>
    /// BuildID uniquely identifies a particular crate build/version.
    /// This value should have no spaces and only have '.', '_', or '-' (and starts and ends with an alpha-numeric)
    /// By convention, the format is "yyMMdd-{VersionID}" (so that sorting by BuildID string yields the most recent release).
    /// e.g. "210320-v0.1.11"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BuildID {
      get { return buildID_; }
      set {
        buildID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "URL" field.</summary>
    public const int URLFieldNumber = 50;
    private string uRL_ = "";
    /// <summary>
    /// URL is an optional string available to specifying a means to access this crate.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string URL {
      get { return uRL_; }
      set {
        uRL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CrateInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CrateInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InstID != other.InstID) return false;
      if (HomeDomain != other.HomeDomain) return false;
      if (NameID != other.NameID) return false;
      if (Title != other.Title) return false;
      if (ShortDesc != other.ShortDesc) return false;
      if (Tags != other.Tags) return false;
      if (TimeCreated != other.TimeCreated) return false;
      if (TimeBuilt != other.TimeBuilt) return false;
      if (MajorVersion != other.MajorVersion) return false;
      if (MinorVersion != other.MinorVersion) return false;
      if (BuildNumber != other.BuildNumber) return false;
      if (BuildID != other.BuildID) return false;
      if (URL != other.URL) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (InstID != 0) hash ^= InstID.GetHashCode();
      if (HomeDomain.Length != 0) hash ^= HomeDomain.GetHashCode();
      if (NameID.Length != 0) hash ^= NameID.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (ShortDesc.Length != 0) hash ^= ShortDesc.GetHashCode();
      if (Tags.Length != 0) hash ^= Tags.GetHashCode();
      if (TimeCreated != 0L) hash ^= TimeCreated.GetHashCode();
      if (TimeBuilt != 0L) hash ^= TimeBuilt.GetHashCode();
      if (MajorVersion != 0) hash ^= MajorVersion.GetHashCode();
      if (MinorVersion != 0) hash ^= MinorVersion.GetHashCode();
      if (BuildNumber != 0) hash ^= BuildNumber.GetHashCode();
      if (BuildID.Length != 0) hash ^= BuildID.GetHashCode();
      if (URL.Length != 0) hash ^= URL.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InstID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(InstID);
      }
      if (HomeDomain.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(HomeDomain);
      }
      if (NameID.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NameID);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Title);
      }
      if (ShortDesc.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ShortDesc);
      }
      if (Tags.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(Tags);
      }
      if (TimeCreated != 0L) {
        output.WriteRawTag(240, 1);
        output.WriteInt64(TimeCreated);
      }
      if (TimeBuilt != 0L) {
        output.WriteRawTag(248, 1);
        output.WriteInt64(TimeBuilt);
      }
      if (MajorVersion != 0) {
        output.WriteRawTag(192, 2);
        output.WriteInt32(MajorVersion);
      }
      if (MinorVersion != 0) {
        output.WriteRawTag(200, 2);
        output.WriteInt32(MinorVersion);
      }
      if (BuildNumber != 0) {
        output.WriteRawTag(208, 2);
        output.WriteInt32(BuildNumber);
      }
      if (BuildID.Length != 0) {
        output.WriteRawTag(234, 2);
        output.WriteString(BuildID);
      }
      if (URL.Length != 0) {
        output.WriteRawTag(146, 3);
        output.WriteString(URL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InstID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(InstID);
      }
      if (HomeDomain.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(HomeDomain);
      }
      if (NameID.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NameID);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Title);
      }
      if (ShortDesc.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ShortDesc);
      }
      if (Tags.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(Tags);
      }
      if (TimeCreated != 0L) {
        output.WriteRawTag(240, 1);
        output.WriteInt64(TimeCreated);
      }
      if (TimeBuilt != 0L) {
        output.WriteRawTag(248, 1);
        output.WriteInt64(TimeBuilt);
      }
      if (MajorVersion != 0) {
        output.WriteRawTag(192, 2);
        output.WriteInt32(MajorVersion);
      }
      if (MinorVersion != 0) {
        output.WriteRawTag(200, 2);
        output.WriteInt32(MinorVersion);
      }
      if (BuildNumber != 0) {
        output.WriteRawTag(208, 2);
        output.WriteInt32(BuildNumber);
      }
      if (BuildID.Length != 0) {
        output.WriteRawTag(234, 2);
        output.WriteString(BuildID);
      }
      if (URL.Length != 0) {
        output.WriteRawTag(146, 3);
        output.WriteString(URL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (InstID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InstID);
      }
      if (HomeDomain.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HomeDomain);
      }
      if (NameID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameID);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (ShortDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ShortDesc);
      }
      if (Tags.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tags);
      }
      if (TimeCreated != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TimeCreated);
      }
      if (TimeBuilt != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TimeBuilt);
      }
      if (MajorVersion != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(MajorVersion);
      }
      if (MinorVersion != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(MinorVersion);
      }
      if (BuildNumber != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(BuildNumber);
      }
      if (BuildID.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(BuildID);
      }
      if (URL.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(URL);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CrateInfo other) {
      if (other == null) {
        return;
      }
      if (other.InstID != 0) {
        InstID = other.InstID;
      }
      if (other.HomeDomain.Length != 0) {
        HomeDomain = other.HomeDomain;
      }
      if (other.NameID.Length != 0) {
        NameID = other.NameID;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.ShortDesc.Length != 0) {
        ShortDesc = other.ShortDesc;
      }
      if (other.Tags.Length != 0) {
        Tags = other.Tags;
      }
      if (other.TimeCreated != 0L) {
        TimeCreated = other.TimeCreated;
      }
      if (other.TimeBuilt != 0L) {
        TimeBuilt = other.TimeBuilt;
      }
      if (other.MajorVersion != 0) {
        MajorVersion = other.MajorVersion;
      }
      if (other.MinorVersion != 0) {
        MinorVersion = other.MinorVersion;
      }
      if (other.BuildNumber != 0) {
        BuildNumber = other.BuildNumber;
      }
      if (other.BuildID.Length != 0) {
        BuildID = other.BuildID;
      }
      if (other.URL.Length != 0) {
        URL = other.URL;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            InstID = input.ReadUInt32();
            break;
          }
          case 26: {
            HomeDomain = input.ReadString();
            break;
          }
          case 42: {
            NameID = input.ReadString();
            break;
          }
          case 82: {
            Title = input.ReadString();
            break;
          }
          case 90: {
            ShortDesc = input.ReadString();
            break;
          }
          case 122: {
            Tags = input.ReadString();
            break;
          }
          case 240: {
            TimeCreated = input.ReadInt64();
            break;
          }
          case 248: {
            TimeBuilt = input.ReadInt64();
            break;
          }
          case 320: {
            MajorVersion = input.ReadInt32();
            break;
          }
          case 328: {
            MinorVersion = input.ReadInt32();
            break;
          }
          case 336: {
            BuildNumber = input.ReadInt32();
            break;
          }
          case 362: {
            BuildID = input.ReadString();
            break;
          }
          case 402: {
            URL = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            InstID = input.ReadUInt32();
            break;
          }
          case 26: {
            HomeDomain = input.ReadString();
            break;
          }
          case 42: {
            NameID = input.ReadString();
            break;
          }
          case 82: {
            Title = input.ReadString();
            break;
          }
          case 90: {
            ShortDesc = input.ReadString();
            break;
          }
          case 122: {
            Tags = input.ReadString();
            break;
          }
          case 240: {
            TimeCreated = input.ReadInt64();
            break;
          }
          case 248: {
            TimeBuilt = input.ReadInt64();
            break;
          }
          case 320: {
            MajorVersion = input.ReadInt32();
            break;
          }
          case 328: {
            MinorVersion = input.ReadInt32();
            break;
          }
          case 336: {
            BuildNumber = input.ReadInt32();
            break;
          }
          case 362: {
            BuildID = input.ReadString();
            break;
          }
          case 402: {
            URL = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// CrateManifest is the top-level manifest/catalog for a PLAN asset module called a "crate".  
  /// It contains catalog and type info that PLAN loads at runtime to know what's inside binary asset bundles without having to load them.
  ///
  /// A reference to a PLAN asset is via an asset URI ("PID") having the form:
  ///   assetURI := "crateDomainName/crateNameID[@crateBuildID]/assetNameID"
  /// 
  /// </summary>
  public sealed partial class CrateManifest : pb::IMessage<CrateManifest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CrateManifest> _parser = new pb::MessageParser<CrateManifest>(() => new CrateManifest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CrateManifest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlanSDK.Crates.CratesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrateManifest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrateManifest(CrateManifest other) : this() {
      info_ = other.info_ != null ? other.info_.Clone() : null;
      iconBundleName_ = other.iconBundleName_;
      bundles_ = other.bundles_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrateManifest Clone() {
      return new CrateManifest(this);
    }

    /// <summary>Field number for the "Info" field.</summary>
    public const int InfoFieldNumber = 1;
    private global::PlanSDK.Crates.CrateInfo info_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PlanSDK.Crates.CrateInfo Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    /// <summary>Field number for the "IconBundleName" field.</summary>
    public const int IconBundleNameFieldNumber = 5;
    private string iconBundleName_ = "";
    /// <summary>
    /// IconBundleName is the bundle name ID of the bundle containing icons (Sprites) used to represent the "real" crate assets.
    /// Asset name IDs in this bundle correspond to assets in all the other Crate's bundles.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IconBundleName {
      get { return iconBundleName_; }
      set {
        iconBundleName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Bundles" field.</summary>
    public const int BundlesFieldNumber = 10;
    private static readonly pb::FieldCodec<global::PlanSDK.Crates.BundleManifest> _repeated_bundles_codec
        = pb::FieldCodec.ForMessage(82, global::PlanSDK.Crates.BundleManifest.Parser);
    private readonly pbc::RepeatedField<global::PlanSDK.Crates.BundleManifest> bundles_ = new pbc::RepeatedField<global::PlanSDK.Crates.BundleManifest>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::PlanSDK.Crates.BundleManifest> Bundles {
      get { return bundles_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CrateManifest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CrateManifest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Info, other.Info)) return false;
      if (IconBundleName != other.IconBundleName) return false;
      if(!bundles_.Equals(other.bundles_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (info_ != null) hash ^= Info.GetHashCode();
      if (IconBundleName.Length != 0) hash ^= IconBundleName.GetHashCode();
      hash ^= bundles_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (info_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Info);
      }
      if (IconBundleName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(IconBundleName);
      }
      bundles_.WriteTo(output, _repeated_bundles_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (info_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Info);
      }
      if (IconBundleName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(IconBundleName);
      }
      bundles_.WriteTo(ref output, _repeated_bundles_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      if (IconBundleName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IconBundleName);
      }
      size += bundles_.CalculateSize(_repeated_bundles_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CrateManifest other) {
      if (other == null) {
        return;
      }
      if (other.info_ != null) {
        if (info_ == null) {
          Info = new global::PlanSDK.Crates.CrateInfo();
        }
        Info.MergeFrom(other.Info);
      }
      if (other.IconBundleName.Length != 0) {
        IconBundleName = other.IconBundleName;
      }
      bundles_.Add(other.bundles_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (info_ == null) {
              Info = new global::PlanSDK.Crates.CrateInfo();
            }
            input.ReadMessage(Info);
            break;
          }
          case 42: {
            IconBundleName = input.ReadString();
            break;
          }
          case 82: {
            bundles_.AddEntriesFrom(input, _repeated_bundles_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (info_ == null) {
              Info = new global::PlanSDK.Crates.CrateInfo();
            }
            input.ReadMessage(Info);
            break;
          }
          case 42: {
            IconBundleName = input.ReadString();
            break;
          }
          case 82: {
            bundles_.AddEntriesFrom(ref input, _repeated_bundles_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// CrateSnapshot is a general purpose container to track a set crates and associated build IDs.
  /// </summary>
  public sealed partial class CrateSnapshot : pb::IMessage<CrateSnapshot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CrateSnapshot> _parser = new pb::MessageParser<CrateSnapshot>(() => new CrateSnapshot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CrateSnapshot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PlanSDK.Crates.CratesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrateSnapshot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrateSnapshot(CrateSnapshot other) : this() {
      revID_ = other.revID_;
      downloadURL_ = other.downloadURL_;
      crates_ = other.crates_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrateSnapshot Clone() {
      return new CrateSnapshot(this);
    }

    /// <summary>Field number for the "RevID" field.</summary>
    public const int RevIDFieldNumber = 1;
    private long revID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RevID {
      get { return revID_; }
      set {
        revID_ = value;
      }
    }

    /// <summary>Field number for the "DownloadURL" field.</summary>
    public const int DownloadURLFieldNumber = 3;
    private string downloadURL_ = "";
    /// <summary>
    /// This is a template string where the symbols "CrateDomain", "CrateNameID", "CrateBuildID", "PlatformID" are delimited with { and }.
    /// The symbol "AppStreaming" will be replaced with "file://"
    /// e.g. "http://whatever.com/{CrateDomain}/{CrateNameID}__{CrateBuildID}.{PlatformID}.zip"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DownloadURL {
      get { return downloadURL_; }
      set {
        downloadURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Crates" field.</summary>
    public const int CratesFieldNumber = 10;
    private static readonly pb::FieldCodec<global::PlanSDK.Crates.CrateInfo> _repeated_crates_codec
        = pb::FieldCodec.ForMessage(82, global::PlanSDK.Crates.CrateInfo.Parser);
    private readonly pbc::RepeatedField<global::PlanSDK.Crates.CrateInfo> crates_ = new pbc::RepeatedField<global::PlanSDK.Crates.CrateInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::PlanSDK.Crates.CrateInfo> Crates {
      get { return crates_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CrateSnapshot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CrateSnapshot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RevID != other.RevID) return false;
      if (DownloadURL != other.DownloadURL) return false;
      if(!crates_.Equals(other.crates_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RevID != 0L) hash ^= RevID.GetHashCode();
      if (DownloadURL.Length != 0) hash ^= DownloadURL.GetHashCode();
      hash ^= crates_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RevID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(RevID);
      }
      if (DownloadURL.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DownloadURL);
      }
      crates_.WriteTo(output, _repeated_crates_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RevID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(RevID);
      }
      if (DownloadURL.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DownloadURL);
      }
      crates_.WriteTo(ref output, _repeated_crates_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RevID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RevID);
      }
      if (DownloadURL.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DownloadURL);
      }
      size += crates_.CalculateSize(_repeated_crates_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CrateSnapshot other) {
      if (other == null) {
        return;
      }
      if (other.RevID != 0L) {
        RevID = other.RevID;
      }
      if (other.DownloadURL.Length != 0) {
        DownloadURL = other.DownloadURL;
      }
      crates_.Add(other.crates_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RevID = input.ReadInt64();
            break;
          }
          case 26: {
            DownloadURL = input.ReadString();
            break;
          }
          case 82: {
            crates_.AddEntriesFrom(input, _repeated_crates_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RevID = input.ReadInt64();
            break;
          }
          case 26: {
            DownloadURL = input.ReadString();
            break;
          }
          case 82: {
            crates_.AddEntriesFrom(ref input, _repeated_crates_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
